### ISSUE TITLE
Operaciones Juan Pablo César Hernández Santiago 1A sistemas 

### ISSUE THREAD

**Issue by Juan27231** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Juan27231#1]
[Operaciones Juan Pablo César Hernández Santiago 1A Sistemas.pdf](https://github.com/user-attachments/files/16841432/Operaciones.Juan.Pablo.Cesar.Hernandez.Santiago.1A.Sistemas.pdf)

**Comment by josealfredo79** [comment]
ortada:22/25
Procedimiento:24/25
Figuras ilustraciones y fotografias :25/25
Resultados y conclusiones:24/25
Calificacion final:19
